using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Shooting : MonoBehaviour
{
    public Camera FPS_Camera;
 
    public GameObject hitEffectPrefab;
 
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
 
    public void Fire()
    {
        RaycastHit _hit;
        Ray ray = FPS_Camera.ViewportPointToRay(new Vector3(0.5f,0.5f));

        if (Physics.Raycast(ray,out _hit,100))
        {
            Debug.Log(_hit.collider.gameObject.name);
 
	    GameObject hitEffectGameobject = Instantiate(hitEffectPrefab, _hit.point, Quaternion.identity);
	    Destroy(hitEffectGameobject, 0.5f);
        }
    }
}
